name: Deploy Docker to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'kb-api-service'   # Your Azure Web App name
  DOCKER_IMAGE_NAME: 'kb-api-image'      # Your Docker image name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -f Dockerfile .

      - name: Deploy to Azure Web App
        uses: azure/webapps-container-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          startup-command: "uvicorn main:app --host 0.0.0.0 --port 7860 --workers 4"
