name: Build and deploy Python app to Azure Web App - kb-api-serivice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # REMOVE the dependency installation - let Azure handle it
      # - name: Create and start virtual environment
      # - name: Install dependencies

      - name: Zip artifact for deployment (app directory only)
        run: |
          cd app
          ls -la  # Debug: show what files are being packaged
          echo "Contents of requirements.txt:"
          head -10 requirements.txt
          zip -r ../release.zip . -x "__pycache__/*" "*.pyc" ".env" "*.log"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'kb-api-serivice'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
