name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with Git LFS support
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # Enable Git LFS support

      # Install Git LFS to handle large files
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      # Set Git user identity
      - name: Configure Git
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      # Track large files and push them to the Hugging Face Hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs track "*.sqlite3"  # Replace with the extension(s) of your large files
          git add .
          git commit -m "Add large files"
          git push https://OxbridegeEcon:$HF_TOKEN@huggingface.co/spaces/Oxbridge-Economics/Mailbox main --force